name: レビュアー追加

on:
  pull_request:
    types: [review_requested]

defaults:
  run:
    shell: bash

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: cat ${GITHUB_EVENT_PATH}
      - run: printenv

  add-reviewer:
    if: ${{ github.event.sender.login != 'Copilot' }}
    runs-on: ubuntu-latest
    steps:
      - id: check-rereview
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            const prNumber = context.payload.pull_request.number;
            const requestedReviewer = context.payload.requested_reviewer.login;

            const {data:reviews} = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            const isReReview = reviews.some(review => review.user.login === requestedReviewer)
            if (isReReview) {
              console.log(`[Result] ${requestedReviewer}さんは過去にレビュー済みです。これは「リレビュー」です。`);
            } else {
              console.log(`[Result] ${requestedReviewer}さんは過去にレビューしていません。これは「初回レビュー」です。`);
            }
            return isReReview;

      - if: steps.check-rereview.outputs.result == 'true'
        run: echo "リレビューが必要です。"
